### ISSUE TITLE
web address

### ISSUE THREAD

**Issue by ghost** [SQLab/PEaaS#6]
if someone know the file name(already run FL and the result hasn't cleared yet) and modify web address can directly jump to results

直接改web address的c/cpp那邊的名字會跳到結果

**Comment by ghost** [comment]
possible method:  網址加密filename 讓它顯示成亂碼

給一個以時間為 seed  的亂數。

**Comment by skhuang** [comment]
可能限制當初進行 fault ranking  的 session 才可以存取。 

//啟動 fault ranking  的程式
session_start();
$randinfo = rand();
$_SESSION['faultranking']= $randinfo;

// pass $randinfo to the results script by GET or POST

//產生 fault ranking  結果的程式
$randinfo = $_REQUEST['randinfo'];
if ($_SESSION['faultranking']== $randinfo) {
// output results
}
