### ISSUE TITLE
'/usr/bin/sudo /bin/su'

### ISSUE THREAD

**Issue by ghost** [SQLab/PEaaS#8]
用完之後 GCOV 會失敗
老師之前看到的結果是之前沒刪除的舊結果

**Comment by skhuang** [comment]
殺檔案的地方也要 sudo su penobody  來殺?

**Comment by ghost** [comment]
time out的才會殺檔案
但是沒TIME OUT的也從能跑變不能跑了...

**Comment by skhuang** [comment]
gcc 也要 sudo 執行，這樣執行時 gcov 相關檔才能寫。

**Comment by ghost** [comment]
是'/usr/bin/sudo /bin/su gcc -fprofile-arcs -ftest-coverage ....'嗎
如果是的話  我加了以後好像連COMPILE的東西都變沒跑出來...

**Comment by skhuang** [comment]
Please use diff to see my revisions:
  diff faultloc_abpath.py faultloc_abpath.py.orig
  diff FL.php FL-orig.php

Several modifications
1. I appended randinfo to the filename to use different path for each session. 
2. chmod 1777 to ufiles.
3. add back sudo to change user to run target programs.

**Comment by ghost** [comment]
time out殺檔案的2行
    os.system("bash -c 'kill -s SIGUSR1 %i'" %p.pid)
    os.system('kill %i' %p.pid)
貌似沒執行到?
或許也要加'/usr/bin/sudo /bin/su'

**Comment by ghost** [comment]
無窮迴圈刪不掉還是存在

/bin/kill -s SIGUSR1 說command not found

/bin/kill 則是沒權限的樣子

**Comment by skhuang** [comment]
用 pgrep -u penobody -l

pgrep -u penobody  470430732loop
可取得所有 pid
